serviceAccount:
  name: ${nginx_service_account_name}
controller:
  service:
    type: ${nginx_service_type}

  admissionWebhooks:
    enabled: false

  ingressClassResource:
    default: true
  %{~ if enable_tailscale_tunnel || enable_cloudflare_tunnel ~}
  extraContainers:
  %{~ endif ~}
    %{~ if enable_cloudflare_tunnel ~}
    - name: cloudflared
      image: "ghcr.io/cloudflare/cloudflared:latest"
      imagePullPolicy: Always
      args:
        - "tunnel"
        - "run"
        - "local"
      env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-token
              key: tunnelToken
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
    %{~ endif ~}
    %{~ if enable_tailscale_tunnel ~}  
    - name: tailscale-sidecar
      imagePullPolicy: Always
      image: "ghcr.io/tailscale/tailscale:latest"
      env:
      %{~ if tailscale_hostname != null ~}
      - name: TS_HOSTNAME
        value: ${tailscale_hostname}
      %{~ endif ~}
      - name: TS_KUBE_SECRET
        value: tailscale-auth-state
      - name: TS_USERSPACE
        value: "false"
      - name: TS_AUTH_KEY
        valueFrom:
          secretKeyRef:
            name: tailscale-auth-key
            key: authKey
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
    %{~ endif ~}
