ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ${cert_issuer_name}
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - ${grafana_fqdn}
  tls:
  - hosts:
    - ${grafana_fqdn}
    secretName: grafana-tls-secret

persistence:
  enabled: true
  size: ${grafana_volume_size}

datasources:
  datasource.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus:9090
        jsonData:
          manageAlerts: false
          prometheusType: Prometheus
          prometheusVersion: '0.73.2'

%{~ if enable_github_oauth ~}
envFromSecret: ${github_oauth_secret_name}
%{~ endif ~}

grafana.ini:
  server:
    root_url: "https://%(domain)s"

  users:
    default_theme: light
    allow_sign_up: false

  %{~ if enable_github_oauth ~}
  auth.github:
    enabled: true
    allow_sign_up: true
    auto_login: true
    allowed_organizations: ${allowed_github_organization}
    role_attribute_path: contains(groups[*], '@${allowed_github_organization}/grafana-admins') && 'Admin' || 'Viewer'
    client_id: $__env{GITHUB_OAUTH_CLIENT_ID}
    client_secret: $__env{GITHUB_OAUTH_CLIENT_SECRET}
  %{~ endif ~}
